// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: core/v1/core.proto

package core

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Stat struct {
	Skill                string   `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	CurrentXp            int64    `protobuf:"varint,2,opt,name=currentXp,proto3" json:"currentXp,omitempty"`
	CurrentRank          int64    `protobuf:"varint,3,opt,name=currentRank,proto3" json:"currentRank,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stat) Reset()         { *m = Stat{} }
func (m *Stat) String() string { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()    {}
func (*Stat) Descriptor() ([]byte, []int) {
	return fileDescriptor_69ce5cdfa1c82ef7, []int{0}
}
func (m *Stat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stat.Unmarshal(m, b)
}
func (m *Stat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stat.Marshal(b, m, deterministic)
}
func (m *Stat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stat.Merge(m, src)
}
func (m *Stat) XXX_Size() int {
	return xxx_messageInfo_Stat.Size(m)
}
func (m *Stat) XXX_DiscardUnknown() {
	xxx_messageInfo_Stat.DiscardUnknown(m)
}

var xxx_messageInfo_Stat proto.InternalMessageInfo

func (m *Stat) GetSkill() string {
	if m != nil {
		return m.Skill
	}
	return ""
}

func (m *Stat) GetCurrentXp() int64 {
	if m != nil {
		return m.CurrentXp
	}
	return 0
}

func (m *Stat) GetCurrentRank() int64 {
	if m != nil {
		return m.CurrentRank
	}
	return 0
}

func (m *Stat) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type SendStatsRequest struct {
	CharacterName        string   `protobuf:"bytes,1,opt,name=characterName,proto3" json:"characterName,omitempty"`
	Stats                []*Stat  `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStatsRequest) Reset()         { *m = SendStatsRequest{} }
func (m *SendStatsRequest) String() string { return proto.CompactTextString(m) }
func (*SendStatsRequest) ProtoMessage()    {}
func (*SendStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69ce5cdfa1c82ef7, []int{1}
}
func (m *SendStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStatsRequest.Unmarshal(m, b)
}
func (m *SendStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStatsRequest.Marshal(b, m, deterministic)
}
func (m *SendStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStatsRequest.Merge(m, src)
}
func (m *SendStatsRequest) XXX_Size() int {
	return xxx_messageInfo_SendStatsRequest.Size(m)
}
func (m *SendStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendStatsRequest proto.InternalMessageInfo

func (m *SendStatsRequest) GetCharacterName() string {
	if m != nil {
		return m.CharacterName
	}
	return ""
}

func (m *SendStatsRequest) GetStats() []*Stat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type SendStatsResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStatsResponse) Reset()         { *m = SendStatsResponse{} }
func (m *SendStatsResponse) String() string { return proto.CompactTextString(m) }
func (*SendStatsResponse) ProtoMessage()    {}
func (*SendStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69ce5cdfa1c82ef7, []int{2}
}
func (m *SendStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStatsResponse.Unmarshal(m, b)
}
func (m *SendStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStatsResponse.Marshal(b, m, deterministic)
}
func (m *SendStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStatsResponse.Merge(m, src)
}
func (m *SendStatsResponse) XXX_Size() int {
	return xxx_messageInfo_SendStatsResponse.Size(m)
}
func (m *SendStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendStatsResponse proto.InternalMessageInfo

func (m *SendStatsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Stat)(nil), "core.Stat")
	proto.RegisterType((*SendStatsRequest)(nil), "core.SendStatsRequest")
	proto.RegisterType((*SendStatsResponse)(nil), "core.SendStatsResponse")
}

func init() { proto.RegisterFile("core/v1/core.proto", fileDescriptor_69ce5cdfa1c82ef7) }

var fileDescriptor_69ce5cdfa1c82ef7 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x26, 0xa9, 0xe8, 0x45, 0x15, 0x70, 0x42, 0xc5, 0x42, 0x0c, 0x56, 0xc4, 0x10,
	0x09, 0xa9, 0x15, 0x65, 0xec, 0x04, 0x6c, 0x0c, 0x0c, 0xce, 0x82, 0xba, 0x19, 0xf7, 0x24, 0xaa,
	0x86, 0x38, 0xd8, 0x4e, 0x7e, 0x3f, 0x72, 0x6c, 0x44, 0x81, 0xc9, 0xf7, 0xde, 0xd3, 0x7d, 0x77,
	0x3e, 0x40, 0xa5, 0x0d, 0xad, 0x86, 0xbb, 0x95, 0x7f, 0x97, 0x9d, 0xd1, 0x4e, 0x63, 0xe6, 0xeb,
	0xd2, 0x40, 0x56, 0x3b, 0xe9, 0xf0, 0x02, 0x72, 0x7b, 0xd8, 0x37, 0x0d, 0x4b, 0x78, 0x52, 0xcd,
	0x44, 0x10, 0x78, 0x0d, 0x33, 0xd5, 0x1b, 0x43, 0xad, 0x7b, 0xed, 0xd8, 0x84, 0x27, 0x55, 0x2a,
	0x7e, 0x0c, 0xe4, 0x50, 0x44, 0x21, 0x64, 0x7b, 0x60, 0xe9, 0x98, 0x1f, 0x5b, 0x9e, 0xda, 0xd0,
	0x40, 0x0d, 0xcb, 0x78, 0x52, 0xe5, 0x22, 0x88, 0x72, 0x0b, 0x67, 0x35, 0xb5, 0x3b, 0x3f, 0xd7,
	0x0a, 0xfa, 0xec, 0xc9, 0x3a, 0xbc, 0x81, 0xb9, 0x7a, 0x97, 0x46, 0x2a, 0x47, 0xe6, 0x45, 0x7e,
	0x50, 0xdc, 0xe3, 0xb7, 0x89, 0x1c, 0x72, 0xeb, 0xbb, 0xd8, 0x84, 0xa7, 0x55, 0xb1, 0x86, 0xe5,
	0xf8, 0x1f, 0x0f, 0x12, 0x21, 0x28, 0x6f, 0xe1, 0xfc, 0x88, 0x6d, 0x3b, 0xdd, 0x5a, 0xc2, 0x05,
	0x4c, 0x7d, 0xda, 0xdb, 0x48, 0x8d, 0x6a, 0xfd, 0x0c, 0xc5, 0x93, 0x36, 0x54, 0x93, 0x19, 0xf6,
	0x8a, 0x70, 0x03, 0x27, 0x0f, 0xbb, 0xd0, 0x8a, 0x8b, 0x88, 0xfe, 0xb3, 0xe7, 0xd5, 0xe5, 0x3f,
	0x3f, 0xcc, 0x78, 0x3c, 0xdd, 0xce, 0xbf, 0x8f, 0xbc, 0xf1, 0xc5, 0xdb, 0x74, 0x3c, 0xf3, 0xfd,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x3b, 0xe0, 0xe8, 0x7c, 0x01, 0x00, 0x00,
}
